# Generated by Django 6.0.2 on 2026-02-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tarifa (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=50)),
                ('numero_veiculo', models.IntegerField()),
                ('capacidade_total', models.IntegerField()),
                ('ano', models.PositiveSmallIntegerField()),
                ('acessibilidade', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentido', models.CharField(max_length=30)),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tempo', models.DurationField()),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noponto.linha')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('dia_semana', models.CharField(max_length=15)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noponto.linha')),
                ('onibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noponto.onibus')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noponto.rota')),
            ],
        ),
    ]
